### ISSUE TITLE
Show what the overall number of exposures that still needs to be inspected and percentage completed

### ISSUE THREAD

**Issue by bruno-moraes** [pmelchior/des-exp-checker#80]
It would be good to know what is our collective target and how far away we are from it.

Thanks!

**Comment by pmelchior** [comment]
We had this in the beginning and phased it out because it looks depressing. Only a small fraction of the images have been inspected, but that doesn't diminish the utility because we don't need to be complete. The tool is for discovering flaws, algorithms are for precise quantitative results (like: "n % of **all** DES images show problem X")

**Comment by bruno-moraes** [comment]
OK, thanks for the reply.
